<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_B-1</name>
   <tag></tag>
   <elementGuidId>3b46abd9-f8f3-4b0a-ae23-fa3359a3979f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Blok B'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a063d694-9a46-4647-b28e-a9a6e4de90f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-default disabled not-pointer</value>
      <webElementGuid>c625b9f9-0494-4eba-8393-c0bb9f4a2fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>NTYwNDg1Mw==</value>
      <webElementGuid>d5efe0ee-2752-477c-8cac-1a2e755ed174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-catid</name>
      <type>Main</type>
      <value>3424</value>
      <webElementGuid>ad045bd2-314f-4cc7-9bbf-61f6bfab607c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6912a239-9de7-4749-8481-d5697c25a5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>B-1</value>
      <webElementGuid>a0c1944f-52a7-40c3-a884-29a32c7d6bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container marketing&quot;]/div[@class=&quot;row if-data-ticket event-menu-tab&quot;]/div[@class=&quot;col-md-8&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 if-show-map-3424&quot;]/div[@class=&quot;row seat-map-3424&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;seatmap&quot;]/span[@class=&quot;btn btn-xs btn-default disabled not-pointer&quot;]</value>
      <webElementGuid>5de363ce-8dfa-4667-9486-e35c32b045ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blok B'])[1]/following::span[1]</value>
      <webElementGuid>011da9c8-ff6d-4709-9870-2d3b973ccf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-50'])[1]/following::span[1]</value>
      <webElementGuid>e6b4e8c2-b90d-457b-9ef2-1d9a4f5776bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B-2'])[1]/preceding::span[1]</value>
      <webElementGuid>808ffd21-92aa-4a19-907b-bdc88ef82d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B-3'])[1]/preceding::span[2]</value>
      <webElementGuid>5b71ad02-a48d-4b88-a35e-02109579dfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='B-1']/parent::*</value>
      <webElementGuid>e44dbf09-1c22-4507-ab83-f92b1a5c6f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[51]</value>
      <webElementGuid>ff500afd-248a-4bd9-a9a3-8ed2b7c5dc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'B-1' or . = 'B-1')]</value>
      <webElementGuid>595c1040-a68e-496a-89e3-87bb4dddc503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
