<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A-38</name>
   <tag></tag>
   <elementGuidId>aabe8afe-4fd3-4b4d-bb53-d784e95c7398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='A-37'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2f522184-f215-466e-b306-d21f75bf840d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-outline-success set-data pointer</value>
      <webElementGuid>86821d01-d230-4800-99cb-1713b499946e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-package</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>acc9c39d-4417-4573-b640-ba8acc792464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>NTYwNDg0MA==</value>
      <webElementGuid>78a84d7f-6b54-4bab-b0b3-180e08780f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-catid</name>
      <type>Main</type>
      <value>3424</value>
      <webElementGuid>62e60ad3-155d-48bc-9094-5ecce20cb7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>786c8aca-12c9-46ca-b3b1-0f30b4461427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A-38</value>
      <webElementGuid>708c09b5-e833-4a20-9635-3ab050bd6bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container marketing&quot;]/div[@class=&quot;row if-data-ticket event-menu-tab&quot;]/div[@class=&quot;col-md-8&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 if-show-map-3424&quot;]/div[@class=&quot;row seat-map-3424&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;seatmap&quot;]/span[@class=&quot;btn btn-xs btn-outline-success set-data pointer&quot;]</value>
      <webElementGuid>bfc4bc1b-a362-4ddb-966d-01d33b4f108d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-37'])[1]/following::span[1]</value>
      <webElementGuid>60873c77-276b-4657-9bfa-853b5531f3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-36'])[1]/following::span[2]</value>
      <webElementGuid>5aa28a70-65d3-49f4-91c9-1c0019669e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-39'])[1]/preceding::span[1]</value>
      <webElementGuid>ab6b6159-9656-4d6d-bfc0-42ce33d7de27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-40'])[1]/preceding::span[2]</value>
      <webElementGuid>d02b5a77-ba22-4c7b-a8ea-da037c323577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A-38']/parent::*</value>
      <webElementGuid>506823e6-a42b-492a-9592-187ef129a2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[38]</value>
      <webElementGuid>4f5cf4fc-a6ad-4388-b3d7-13ca8be0307c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'A-38' or . = 'A-38')]</value>
      <webElementGuid>7fb04f98-e349-4e48-8d7c-6bf60a5a3cbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
