<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QRIS</name>
   <tag></tag>
   <elementGuidId>07f8f07c-9feb-41e5-b93f-147c66b4b8df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-item.nav-link.nav-link.nav-link-payment.pointer.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'QRIS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da085915-00e6-4da7-8832-d2082a8c3526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link nav-link nav-link-payment pointer active</value>
      <webElementGuid>b1098bd6-0bbe-4d1c-b729-8342a74d12ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>qris</value>
      <webElementGuid>42a852f9-2676-4afe-9c34-f218b940e7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QRIS</value>
      <webElementGuid>4459b85e-989d-454f-be9c-055b5aa77737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container marketing&quot;]/div[@class=&quot;row if-data-payment event-menu-tab&quot;]/div[@class=&quot;col-md-8 col-8-nav&quot;]/div[@class=&quot;row row-nav-link&quot;]/nav[@class=&quot;nav nav-pills nav-justified&quot;]/a[@class=&quot;nav-item nav-link nav-link nav-link-payment pointer active&quot;]</value>
      <webElementGuid>d56cf068-1f56-40a4-87ed-c34b6b7f696c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QRIS')]</value>
      <webElementGuid>ddc24979-74f2-434d-a77d-a96342512ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convenience Store'])[1]/following::a[1]</value>
      <webElementGuid>ff75db76-33b0-4991-b877-6d18c6247b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Wallet'])[1]/following::a[2]</value>
      <webElementGuid>8c4215fe-8310-4f23-ab46-a2eaa3f1d33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANK MANDIRI Virtual Account'])[1]/preceding::a[1]</value>
      <webElementGuid>a009d8e6-8850-49bd-93a7-de157d977897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANK CIMB NIAGA Virtual Account'])[1]/preceding::a[1]</value>
      <webElementGuid>edc8376b-9b42-4600-bbcf-55853924ef8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QRIS']/parent::*</value>
      <webElementGuid>e6203189-d0de-4b52-a76c-a4fdf96fafa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>b76ceb6a-732f-48e9-b16b-0c5f6cd80c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'QRIS' or . = 'QRIS')]</value>
      <webElementGuid>3f61425f-c30b-4de6-99dd-78aef951da18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
