<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A-22</name>
   <tag></tag>
   <elementGuidId>ce7d6cc1-84f6-4949-9676-34b2db12f8dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='A-21'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31738d04-4ece-4e55-8c8e-7a1477a97991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-outline-success set-data pointer</value>
      <webElementGuid>df439ae1-fdd6-4ed8-b867-fd4f066ee57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-package</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>739ae3bd-9b33-414a-9154-678fb90bd9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>NTYwNDgyNA==</value>
      <webElementGuid>070b8200-676f-487b-a977-68ca5b641508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-catid</name>
      <type>Main</type>
      <value>3424</value>
      <webElementGuid>45fbf222-04a5-4cb1-9883-9bac37b44432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>fd94ffa0-4bf6-4ac7-8307-0920a0aeb85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A-22</value>
      <webElementGuid>4b814c89-e88e-417d-aa9a-d01195b45062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container marketing&quot;]/div[@class=&quot;row if-data-ticket event-menu-tab&quot;]/div[@class=&quot;col-md-8&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 if-show-map-3424&quot;]/div[@class=&quot;row seat-map-3424&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;seatmap&quot;]/span[@class=&quot;btn btn-xs btn-outline-success set-data pointer&quot;]</value>
      <webElementGuid>ca75f4f8-d789-4220-8830-15cf12992cf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-21'])[1]/following::span[1]</value>
      <webElementGuid>17ae2c3d-e1f5-4e31-a67f-24329ef1c959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-20'])[1]/following::span[2]</value>
      <webElementGuid>df4a1450-6d88-4529-b8e5-3f5f18964392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-23'])[1]/preceding::span[1]</value>
      <webElementGuid>3852cfae-6493-4934-9abd-4a7d124949d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-24'])[1]/preceding::span[2]</value>
      <webElementGuid>3a0f6a92-14d4-41fc-80ca-b849b772006c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A-22']/parent::*</value>
      <webElementGuid>711f3e37-93c6-40a3-a1f7-9dafa75323a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[22]</value>
      <webElementGuid>4880fbed-98b5-45e0-b397-3dbe299b6a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'A-22' or . = 'A-22')]</value>
      <webElementGuid>976f5b0f-7a6a-4ea7-a04b-8ce0ffa865da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
