<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A-17</name>
   <tag></tag>
   <elementGuidId>866e90d6-75c8-4748-8fe1-7cb03f09782c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='A-16'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65ecb161-7304-4692-acc3-4c3fed68b5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-outline-success set-data pointer</value>
      <webElementGuid>4a2462e4-9e4f-490b-9d30-25f19ae39dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-package</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b86cea3f-6ebe-4f51-94a6-6c5cb1d29a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>NTYwNDgxOQ==</value>
      <webElementGuid>f78c7276-adf5-41cd-9c13-00942a807b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-catid</name>
      <type>Main</type>
      <value>3424</value>
      <webElementGuid>e08e676c-1326-4b1d-bb85-8eabc262ba96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6598a82e-2245-48a8-b4b2-dbb950366187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A-17</value>
      <webElementGuid>9a6509b1-5d87-4930-a163-47f13ed5a879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container marketing&quot;]/div[@class=&quot;row if-data-ticket event-menu-tab&quot;]/div[@class=&quot;col-md-8&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 if-show-map-3424&quot;]/div[@class=&quot;row seat-map-3424&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;seatmap&quot;]/span[@class=&quot;btn btn-xs btn-outline-success set-data pointer&quot;]</value>
      <webElementGuid>23849756-33ff-48b3-950d-bfb90d6e7c85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-16'])[1]/following::span[1]</value>
      <webElementGuid>c2d4d020-5521-4494-9466-d67930ac55c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-15'])[1]/following::span[2]</value>
      <webElementGuid>a8144064-d937-4732-92d6-6ebceedfbee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-18'])[1]/preceding::span[1]</value>
      <webElementGuid>966c317d-fc88-4dd2-86d2-cb83228f42a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-19'])[1]/preceding::span[2]</value>
      <webElementGuid>7077fd22-1d8a-4dad-a0ab-dbe9ee8f5d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A-17']/parent::*</value>
      <webElementGuid>49fcebfe-ad7a-4d01-9ac7-3fb4a9986d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[17]</value>
      <webElementGuid>ea7fd65a-2b1e-4093-9a61-5cb5e5a14eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'A-17' or . = 'A-17')]</value>
      <webElementGuid>c95fa7ff-aaac-4f48-969d-ecbef90d6632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
