<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir</name>
   <tag></tag>
   <elementGuidId>2bb9d62f-d59f-4226-a9b1-0003ae054315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datetimepicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datetimepicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c06639ce-bd5f-4f44-8280-48637c00db38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ba96a94-1939-4501-b7fe-fe36c0e43a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>26f192db-b440-45a8-ad13-6a5ce8349cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datetimepicker</value>
      <webElementGuid>ea8151b8-09fd-4219-bee3-72a056eefedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>cbf2f224-38e5-4242-b3ac-e381526e7fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datetimepicker&quot;)</value>
      <webElementGuid>5c9e2a57-d241-4585-874d-05a739b93bac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datetimepicker']</value>
      <webElementGuid>bddc367e-9edd-47df-8013-f9b7d808e29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>64bf211b-ebb9-47bf-870d-f5f060ba5207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datetimepicker' and @name = 'dob']</value>
      <webElementGuid>e5ca661a-88d7-4dfe-9d36-5f07798bfae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
