<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A-42</name>
   <tag></tag>
   <elementGuidId>1527958c-30a7-4942-ae00-736fe8d5b3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='A-41'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31f12124-d410-409f-8477-2473a29fd8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-outline-success set-data pointer</value>
      <webElementGuid>e43f2bb8-fa58-49e9-b154-115f020978a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-package</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a338f15-cf75-4f7a-9a75-fcf995dbbf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>NTYwNDg0NA==</value>
      <webElementGuid>fa5a9a24-7d41-47a8-8fda-e2bfe084c51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-catid</name>
      <type>Main</type>
      <value>3424</value>
      <webElementGuid>0dbea4c6-69d5-4380-aad2-868274cb3244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6ab21a72-9621-45b3-897d-0afa3740c43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A-42</value>
      <webElementGuid>b1200294-4f66-4307-9ac7-21ba39241daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container marketing&quot;]/div[@class=&quot;row if-data-ticket event-menu-tab&quot;]/div[@class=&quot;col-md-8&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 if-show-map-3424&quot;]/div[@class=&quot;row seat-map-3424&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;seatmap&quot;]/span[@class=&quot;btn btn-xs btn-outline-success set-data pointer&quot;]</value>
      <webElementGuid>2b611a3b-66ef-45f8-b54f-286f87198157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-41'])[1]/following::span[1]</value>
      <webElementGuid>12be78fa-ab0c-4290-b8e8-97ae1c961443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-40'])[1]/following::span[2]</value>
      <webElementGuid>276d2668-4d11-4b84-9b42-638cc96d0568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-43'])[1]/preceding::span[1]</value>
      <webElementGuid>b5cc3ab6-47a9-42e1-869e-fa03514805d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-44'])[1]/preceding::span[2]</value>
      <webElementGuid>bc244fef-4873-454e-85c1-8c196aef92ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A-42']/parent::*</value>
      <webElementGuid>1176ea78-d31d-43ad-aec6-03c324c5081e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[42]</value>
      <webElementGuid>0d7e0986-42c8-46a0-8375-1f636d86150b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'A-42' or . = 'A-42')]</value>
      <webElementGuid>a6775d15-c9a2-4ecf-9d33-698a4fd8d5c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
