<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Number</name>
   <tag></tag>
   <elementGuidId>0dc0882b-bf7b-43e6-b0b4-513cea9ec0be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardnumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardnumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2fdcdec-5166-4a4b-9182-ea280c880549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardnumber</value>
      <webElementGuid>923aab7d-9ecd-4fa3-bb54-f3545495a33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a818f9bb-fc53-42cd-97f6-7106585e4f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardNo</value>
      <webElementGuid>3d1fb1b1-69bf-4efd-ad40-9984964fae65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardnumber&quot;)</value>
      <webElementGuid>99056716-ffc4-4bf9-a8b8-52cd182fa5ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardnumber']</value>
      <webElementGuid>afe5ee51-b8eb-42f9-a2d3-ff73e7cf860b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2a9c3f39-5430-4123-ab2e-c4713284c4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cardnumber' and @type = 'text' and @name = 'cardNo']</value>
      <webElementGuid>65db71d8-64a3-4bc6-a910-e0fea3a69d8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
