<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration</name>
   <tag></tag>
   <elementGuidId>25c31d79-ed65-40f3-953c-a77e5ecd5dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expirationdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expirationdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>473b8421-46ed-4fa9-b1d1-bf2d3e06b25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expirationdate</value>
      <webElementGuid>d79571c3-e8c6-4324-9df9-bda1fa58d79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a645ea6-1f06-4c3a-a480-582d2ed38398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardExpYymm</value>
      <webElementGuid>ff0d021f-849a-4dd9-ab79-242805621d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>33bc8dd2-bede-47df-9455-7f4156a3ce96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expirationdate&quot;)</value>
      <webElementGuid>9317021c-623d-4c5b-a742-467785843bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expirationdate']</value>
      <webElementGuid>031b898a-4ff5-4cdf-aeb5-f2e95c8ed092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4e7bb4c3-44aa-438e-9200-70e274c16612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expirationdate' and @type = 'text' and @name = 'cardExpYymm']</value>
      <webElementGuid>fb122c05-e438-4077-9ca2-b665f7627630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
