<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security Code</name>
   <tag></tag>
   <elementGuidId>38f80672-4799-41df-aba6-c14daf6111bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#securitycode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securitycode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33fd2673-0be7-458d-bcd4-6704bedc4d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securitycode</value>
      <webElementGuid>1e30afda-1456-4a6b-b320-d0b012dd37a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>71893279-a436-4637-97d4-00eb121a3618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>29b167f9-cf4c-484b-97a8-f7d7703f8a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardCvv</value>
      <webElementGuid>c86e0b5d-93cb-45d4-8b07-35f89b1dbc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>14be3cd7-ad77-46a8-8dfd-a286635ccd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securitycode&quot;)</value>
      <webElementGuid>342fc1b5-b451-4870-8060-2c69b50f1bbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securitycode']</value>
      <webElementGuid>bd84ae26-4235-4e0a-8026-10c853d00e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2f821ffa-5c1c-40a2-8e81-8b61489dc89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'securitycode' and @type = 'password' and @name = 'cardCvv']</value>
      <webElementGuid>99c256fa-46c8-42c5-b696-844e74c98698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
